name: default
fog:
  density: 0.0375
  color: 0x345441
color:
  pow:
    x: 1
    y: 1
    z: 1
  mul:
    x: 1
    y: 1
    z: 1
  add:
    x: 0
    y: 0
    z: 0
saturation: 0
hue: 0
contrast: 0
brightness: 0
bleach: 0
sky: 
  color: 0xbeedfe
ground:
  color: 0x4caf50